port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090

geodata-mode: true
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/country.mmdb"

dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - localhost.ptlogin2.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - +.msftconnecttest.com
    - +.msftncsi.com
    - +.xboxlive.com
    - msftconnecttest.com
    - xbox.*.microsoft.com
    - "*.battlenet.com.cn"
    - "*.battlenet.com"
    - "*.blzstatic.cn"
    - "*.battle.net"
  nameserver:
    - 223.5.5.5
    - 114.114.114.114
  fallback:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4

profile:
  tracing: true

proxy-providers:
  A:
    type: http
    path: ./profiles/proxies/A.yaml
    url: 订阅链接
    interval: 86400
    health-check:
      enable: true
      url: http://www.google.com/generate_204
      interval: 300
  B:
    type: http
    path: ./profiles/proxies/B.yaml
    url: 订阅链接
    interval: 86400
    health-check:
      enable: true
      url: http://www.google.com/generate_204
      interval: 300      
      
proxy-groups:
  - name: Proxy
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Proxy.png
    filter: '^(?!.*((?i)🇭🇰|香港|(\b(HK|Hong)\d{0,2}\b)|🇹🇼|台湾|(\b(TW|Tai|Taiwan)\d{0,2}\b)|🇯🇵|日本|川日|东京|大阪|泉日|埼玉|(\b(JP|Japan)\d{0,2}\b)|🇸🇬|新加坡|狮|(\b(SG|Singapore)\d{0,2}\b)|🇺🇸|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(\b(US|United States)\d{0,2}\b)|(法国|法|巴黎|FR|France)|(英国|英|伦敦|UK|GB|GBR|England|United Kingdom)|(韩国|韩|韓|首尔|KR|KOR|Korea)|(马来西亚|马来|大马|MY|Malaysia)|(德国|法兰克福|DE|Germany)|(泰国|泰|曼谷|TH|Thailand)|(荷兰|荷|尼德兰|阿姆斯特丹|NL|Netherlands)))'
    url: http://www.google.com/generate_204
    interval: 300
    use:
      - B
    proxies:
      - Hong Kong
      - Taiwan
      - Japan
      - Singapore
      - United States
      
  - name: Telegram
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    url: http://www.google.com/generate_204
    interval: 300
    proxies:
      - Hong Kong
      - Taiwan
      - Japan
      - Singapore
      - United States
      - Proxy

  - name: OpenAI
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bot.png
    url: http://www.google.com/generate_204
    interval: 300
    proxies:
      - Hong Kong
      - Taiwan
      - Japan
      - Singapore
      - United States
      - Proxy

  - name: Meta
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Facebook.png
    url: http://www.google.com/generate_204
    interval: 300
    proxies:
      - Hong Kong
      - Taiwan
      - Japan
      - Singapore
      - United States
      - Proxy

  - name: Final
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Final.png
    url: http://www.google.com/generate_204
    interval: 300
    proxies:
      - Proxy
      - Direct
      
  - name: Hong Kong
    type: url-test
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/HK.png
    filter: '^(?=.*((?i)🇭🇰|香港|(\b(HK|Hong)\d{0,2}\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true
    use:
      - A

  - name: Taiwan
    type: url-test
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/TW.png
    filter: '^(?=.*((?i)🇹🇼|台湾|(\b(TW|Tai|Taiwan)\d{0,2}\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true
    use:
      - A

  - name: Japan
    type: url-test
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/JP.png
    filter: '^(?=.*((?i)🇯🇵|日本|川日|东京|大阪|泉日|埼玉|(\b(JP|Japan)\d{0,2}\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true
    use:
      - A

  - name: Singapore
    type: url-test
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/SG.png
    filter: '^(?=.*((?i)🇸🇬|新加坡|狮|(\b(SG|Singapore)\d{0,2}\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true
    use:
      - A

  - name: United States
    type: url-test
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/US.png
    filter: '^(?=.*((?i)🇺🇸|美国|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|(\b(US|United States)\d{0,2}\b)))(?!.*((?i)回国|校园|游戏|🎮|(\b(GAME)\b))).*$'
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true
    use:
      - A

  - name: Direct
    type: url-test
    icon: https://raw.githubusercontent.com/Orz-3/mini/master/Color/CN.png
    url: http://www.google.com/generate_204
    interval: 300
    tolerance: 150
    lazy: true
    hidden: true
    proxies:
      - DIRECT

rule-providers:  
  Unbreak:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Unbreak.yaml
    path: ./ruleset/Unbreak.yaml 
  Reject:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Reject.yaml
    path: ./ruleset/Reject.yaml 
  CN:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/CN.yaml
    path: ./ruleset/CN.yaml 
  Telegram:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Telegram.yaml
    path: ./ruleset/Telegram.yaml 
  OpenAI:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/OpenAI.yaml
    path: ./ruleset/OpenAI.yaml 
  Meta:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Meta.yaml
    path: ./ruleset/Meta.yaml 
  Proxy:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/Proxy.yaml
    path: ./ruleset/Proxy.yaml 
  Proxy+:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Proxy/Proxy_Classical_No_Resolve.yaml
    path: ./ruleset/Proxy+.yaml 
  China:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/China/China_Classical_No_Resolve.yaml
    path: ./ruleset/China.yaml 
  LAN:
    type: http
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/Saw/main/Clash/Providers/LAN.yaml
    path: ./ruleset/LAN.yaml 

rules:
- RULE-SET,Unbreak,DIRECT
- RULE-SET,Reject,REJECT
- RULE-SET,CN,DIRECT
- RULE-SET,Telegram,Telegram
- RULE-SET,OpenAI,OpenAI
- RULE-SET,Meta,Meta
- RULE-SET,Proxy,Proxy
- RULE-SET,Proxy+,Proxy
- RULE-SET,China,DIRECT
- RULE-SET,LAN,DIRECT
- DOMAIN-SUFFIX,cn,DIRECT
- GEOIP,CN,DIRECT
- MATCH,Final


script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
