proxies:
  - name: "Reality"
    type: vless
    server: server
    port: 34567
    uuid: uuid
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.microsoft.com # REALITY servername
    reality-opts:
      public-key: xxx
    client-fingerprint: chrome # cannot be empty
