dns:
  default-nameserver:
  - 119.29.29.29
  - 223.5.5.5
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
log-level: info
mode: rule


proxy-groups:
  - name: 影视媒体
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Media.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线

  - name: 社交媒体
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  
  - name: 音乐平台
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube_Music.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  
  - name: 人工智能
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Bot.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
 
  - name: 通讯软件
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  
  - name: 谷歌云盘
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Drive.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  
  - name: 谷歌服务
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
 
  - name: 微软云盘
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/OneDrive.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  
  - name: 微软服务
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  
  - name: 代理网站
    type: select
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/World_Map.png
    proxies:
      - 香港节点
      - 狮城节点
      - 日本节点
      - 美国节点
      - 香港专线
      - 狮城专线
      - 日本专线
      - 美国专线
  


  - name: 国内直连
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/China.png
    interval: 300
    proxies:
      - DIRECT
    
  - name: 香港节点
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    filter: ".*(?!.*(专线|(.*0\.[1-9]))).*(香港|海港|深港|广港|HK|Hong Kong).*"
    include-all: true
    interval: 300
    lazy: true
    
  - name: 狮城节点
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png
    filter: ".*(?!.*(专线|(.*0\.[1-9]))).*(新加坡|狮城|SG|Singapore).*"
    include-all: true
    interval: 300
    lazy: true
    
  - name: 日本节点
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    filter: ".*(?!.*(专线|(.*0\.[1-9]))).*(日本|东京|大阪|埼玉|JP|Japan).*"
    include-all: true
    interval: 300
    lazy: true    
    
  - name: 美国节点
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    filter: ".*(?!.*(家宽|专线|(.*0\.[1-9]))).*(美国|US|USA|America|United States).*"
    include-all: true
    interval: 300
    lazy: true    
    
  - name: 香港专线
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
    filter: "香港专线"
    include-all: true
    interval: 300
    lazy: true
    
  - name: 狮城专线
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png
    filter: "狮城专线"
    include-all: true
    interval: 300
    lazy: true
    
  - name: 日本专线
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
    filter: "日本专线"
    include-all: true
    interval: 300
    lazy: true    
    
  - name: 美国专线
    type: fallback
    url: http://cp.cloudflare.com/generate_204
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
    filter: "美国专线"
    include-all: true
    interval: 300
    lazy: true  


rule-providers:
  LocalAreaNetwork:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml
  UnBan:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml
  BanAD:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml
  BanProgramAD:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml
  BanEasyListChina:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml
  Telegram:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml
  Ai:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/Saw1g88/ACL4SSR/master/Clash/Providers/Ai.yaml
  YouTubeMusic:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTubeMusic.yaml
  Spotify:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Spotify.yaml
  YouTube:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml
  Porn:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Porn.yaml
  GoogleDrive:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleDrive/GoogleDrive.yaml
  GoogleFCM:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml
  Google:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml
  GoogleCNProxyIP:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCNProxyIP.yaml
  GoogleCN:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml
  Twitter:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Twitter.yaml
  Facebook:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Facebook.yaml
  Instagram:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Instagram.yaml
  OneDrive:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml
  Microsoft:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml
  ProxyLite:
    behavior: classical
    interval: 86400
    type: http
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyLite.yaml
  ChinaDomain:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml
  ChinaCompanyIp:
    behavior: classical
    interval: 86400
    url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml


rules:
- SCRIPT,quic,REJECT
- RULE-SET,LocalAreaNetwork,DIRECT
- RULE-SET,UnBan,DIRECT
- RULE-SET,BanAD,REJECT
- RULE-SET,BanProgramAD,REJECT
- RULE-SET,BanEasyListChina,REJECT
- RULE-SET,Telegram,通讯软件
- RULE-SET,Ai,人工智能
- RULE-SET,YouTubeMusic,音乐平台
- RULE-SET,Spotify,音乐平台
- RULE-SET,YouTube,影视媒体
- RULE-SET,Porn,影视媒体
- RULE-SET,GoogleDrive,谷歌云盘
- RULE-SET,GoogleFCM,谷歌服务
- RULE-SET,Google,谷歌服务
- RULE-SET,GoogleCN,谷歌服务
- RULE-SET,GoogleCNProxyIP,谷歌服务
- RULE-SET,Twitter,社交媒体
- RULE-SET,Facebook,社交媒体
- RULE-SET,Instagram,社交媒体
- RULE-SET,OneDrive,微软云盘
- RULE-SET,Microsoft,微软服务
- RULE-SET,ProxyLite,代理网站
- RULE-SET,ChinaDomain,DIRECT
- RULE-SET,ChinaCompanyIp,DIRECT
- GEOIP,CN,DIRECT
- MATCH,代理网站
script:
  shortcuts:
    quic: network == 'udp' and dst_port == 443
